version: '3.3'

services:
  backend:
    build: ./server
    restart: always
    working_dir: /app
    ports:
      - "5000:5000"
    tty: true
    command: "npm run start"

  front:
    build: ./client
    volumes:
      - front-volume:/app/dist/client
    tty: true

  web-server:
    image: nginx:1.16.0-alpine
    restart: always
    volumes:
      - front-volume:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    working_dir: /app
    depends_on:
      - backend
      - front
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    tty: true

volumes:
  front-volume: